name: Update Tidal Now Playing

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch current Tidal track & update README
        env:
          TIDAL_CLIENT_ID:     ${{ secrets.TIDAL_CLIENT_ID }}
          TIDAL_CLIENT_SECRET: ${{ secrets.TIDAL_CLIENT_SECRET }}
          TIDAL_REFRESH_TOKEN: ${{ secrets.TIDAL_REFRESH_TOKEN }}
        run: python .github/scripts/update_now_playing.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "chore: update Tidal now playing"
          git push
